### ISSUE TITLE
Race condition with “alive status” in Register function

### ISSUE THREAD

**Issue by cmbrandenburg** [nightowlware/iglue#1]
The `Register` function returns an `aliveStatus` value that may be accessed by multiple goroutines without synchronization.

Any fix will require changing the `Register` function's signature, as there's no way for the caller to make use of a raw `*bool`. Even with synchronization, the API lends itself to a time-of-check-to-time-of-use race condition in the caller.

Why not nix the `aliveStatus` return altogether and instead let the caller detect that `iglueChan` has closed?

**Comment by nightowlware** [comment]
Ah yes, this is actually a known issue. I found this out when I ran the (rather excellent) Go race-detector (go test -race).

I agree that aliveStatus is shitty and needs to be nixed. Is there a way to check if a channel is closed without potentially blocking? It seems like the answer is "no". Any other ideas?

**Comment by cmbrandenburg** [comment]
What's the intended use of `aliveStatus`? What useful thing do you expect a caller to be able to do with the information? I predict any use case you imagine will be plagued by a TOCTOU bug.

One thing to consider is that blocking operations aren't a big deal in Go because goroutines are cheap—i.e., spawn a dedicated goroutine to read from `iglueChan`, which would close to signal a shutdown. If the application must read from two or more channels simultaneously then it may use Go's `select` feature.

**Comment by Shafik23** [comment]
Ok, I think you convinced me that I don't really need that status. It's up to clients to deal with the channel's semantics.
